### ISSUE TITLE
Add collaborators to this repo

### ISSUE THREAD

**Issue by fredgohsman** [gh4d/att1#1]
## Comment below to be added as a collaborator

We will all be using this repository today. Even though it's public right now, you will not be able to make changes until you're given the correct permissions. We've automated this process via the GitHub API. Once you comment, we will add you as a collaborator.

You'll start to receive a lot of emails. (❗) You can slow these down immediately by clicking the **Unwatch** button at the top of the page and selecting either the **Participating and @mentions** or **Ignore** option.

**Comment by fredgohsman** [comment]
**Hello!** 👋

**Comment by andersolsson94** [comment]
Greetings

**Comment by dg630s** [comment]
Good afternoon!

**Comment by luzgit2020** [comment]
Hi! This is Luz A joining github training today. Thanks Fred.

**Comment by mk0012673** [comment]
good afternnon!

**Comment by raisabor** [comment]
Good day!

**Comment by dramayrat** [comment]
hi there

**Comment by hp365s** [comment]
Hello

**Comment by sn493s** [comment]
Hello

**Comment by mr8412** [comment]
Hello

**Comment by vs252n** [comment]
Hello

**Comment by dingerpk57** [comment]
dingerpk57
